### ISSUE TITLE
Repository name

### ISSUE THREAD

**Issue by kshchepanovskyi** [antlr/antlr4-intellij-adaptor#8]
I think it makes sense to rename this repository and library to `antlr-jetbrains-adapter` (or something similar).

**Comment by bjansen** [comment]
@parrt I'm also in favor of this. `jetbrains` doesn't speak for itself at all, since it's a company name.

`antlr-intellij-adapter` would be much more meaningful, since the library adapts ANTLR stuff to the IntelliJ platform.

Github automatically redirects old repo names to new names, so it wouldn't even be an issue.

**Comment by parrt** [comment]
Hmm...i think i chose jetbrains as it works on all their platforms not just intellij

**Comment by bjansen** [comment]
JetBrains is the company, IntelliJ is the name of the platform on which IDEs are built, and IntelliJ IDEA is the name of the Java IDE.

Rider, Goland, PhpStorm, PyCharm etc. are all based on the IntelliJ platform, although they don't have 'IntelliJ' in their name.

=> using "intellij" in the repo name doesn't mean it's restricted to IntelliJ IDEA

**Comment by parrt** [comment]
wow, no kidding? ok. I don't have a problem with a name change but can you make sure such a change gets propagated to the other repos that use this?

**Comment by bjansen** [comment]
Relevant link: https://www.jetbrains.com/opensource/idea/

Regarding the GitHub part: https://help.github.com/articles/renaming-a-repository/

> In addition to redirecting web traffic, all git clone, git fetch, or git push operations targeting the previous location will continue to function as if made on the new location. However, to reduce confusion, we strongly recommend updating any existing local clones to point to the new repository URL

**Comment by parrt** [comment]
just getting rolling this AM. More in about an hour.

**Comment by bjansen** [comment]
Also, with https://github.com/antlr/jetbrains/pull/13 we'll be able to publish the library to Central. This means that we'll encourage people to pull a jar instead of using a Git submodule.

**Comment by parrt** [comment]
i renamed to antlr4-intellij-adaptor ('or' not 'er' to be consistent with my codebase)
